// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ElmsDbContext))]
    [Migration("20260609090904_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.TempModels.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaxScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(6, 2)")
                        .HasDefaultValue(100m);

                    b.Property<decimal>("PassingScorePct")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<byte>("SubmissionType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Assignme__3214EC07D9839F64");

                    b.ToTable("Assignment", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.AssignmentWork", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DraftSavedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedbackText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("GradedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GraderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TextAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssignmentId", "StudentId")
                        .HasName("PK__Assignme__B165CCCE4390C321");

                    b.HasIndex("GraderId");

                    b.HasIndex("StudentId");

                    b.ToTable("AssignmentWork", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.AttemptAnswer", b =>
                {
                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChosenOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.HasKey("AttemptId", "ChosenOptionId")
                        .HasName("PK__AttemptA__93BFE65D20CC1582");

                    b.HasIndex("ChosenOptionId");

                    b.ToTable("AttemptAnswer", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Picture")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC07993CDB00");

                    b.HasIndex(new[] { "Name" }, "UQ__Categori__737584F64FC3C943")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("PublishAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Course__3214EC073A17DE83");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.CourseManager", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CourseId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CourseManagers");
                });

            modelBuilder.Entity("Infrastructure.TempModels.CoursePrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EffectiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceAmount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__CoursePr__3214EC07B99E2D14");

                    b.HasIndex(new[] { "CourseId" }, "UQ_CoursePrice_Active_OnePriceOnly")
                        .IsUnique()
                        .HasFilter("([IsActive]=(1))");

                    b.ToTable("CoursePrice", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.CourseRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__CourseRe__3214EC07E863B1BB");

                    b.HasIndex("CourseId");

                    b.HasIndex("ParentId");

                    b.HasIndex(new[] { "StudentId", "CourseId" }, "UQ_CourseRequests_StudentCourse")
                        .IsUnique();

                    b.ToTable("CourseRequests");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Discussion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Discussi__3214EC07F06DF961");

                    b.ToTable("Discussion", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.DiscussionReply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DiscussionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentReplyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Discussi__3214EC075CA3EA89");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DiscussionId");

                    b.HasIndex("ParentReplyId");

                    b.ToTable("DiscussionReplies");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Enrollme__3214EC0779269BF9");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Flashcard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("BackText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("Id")
                        .HasName("PK__Flashcar__3214EC0737C6A2F3");

                    b.HasIndex("SetId");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("Infrastructure.TempModels.FlashcardSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("Id")
                        .HasName("PK__Flashcar__3214EC079963F2DD");

                    b.HasIndex("StudentId");

                    b.ToTable("FlashcardSets");
                });

            modelBuilder.Entity("Infrastructure.TempModels.InstructorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expertise")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualifications")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Instruct__3214EC0746B47B69");

                    b.ToTable("InstructorProfile", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ContentType")
                        .HasColumnType("tinyint");

                    b.Property<int?>("DurationSec")
                        .HasColumnType("int");

                    b.Property<string>("TextContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id")
                        .HasName("PK__Lesson__3214EC071AA94531");

                    b.ToTable("Lesson", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.LessonOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__LessonOp__3214EC072E73BC5F");

                    b.HasIndex("QuestionId");

                    b.ToTable("LessonOption", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.LessonQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__LessonQu__3214EC07DC88D140");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonQuestion", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.ManagerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__ManagerP__3214EC07690C9E3E");

                    b.ToTable("ManagerProfile", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Module__3214EC071960FC2D");

                    b.HasIndex(new[] { "CourseId", "OrderIndex" }, "UQ_Module_CourseOrder")
                        .IsUnique();

                    b.ToTable("Module", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.ModuleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ItemType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__ModuleIt__3214EC0798DF46D0");

                    b.HasIndex(new[] { "ModuleId", "OrderIndex" }, "UQ_ModuleItem_ModuleOrder")
                        .IsUnique();

                    b.ToTable("ModuleItem", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.OauthAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__OAuthAcc__3214EC07C50EB307");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Provider", "ProviderUserId" }, "UQ_OAuth_provider_uid")
                        .IsUnique();

                    b.ToTable("OAuthAccounts", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("PaymentMethod")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.HasKey("Id")
                        .HasName("PK__Orders__3214EC07E3CDB0A4");

                    b.HasIndex("ParentId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Infrastructure.TempModels.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PriceVnd")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__OrderIte__3214EC0700B32BF3");

                    b.HasIndex("CourseId");

                    b.HasIndex("RequestId");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "OrderId", "CourseId", "StudentId" }, "UQ_OrderItems")
                        .IsUnique();

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Otp", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Email")
                        .HasName("PK__Otp__A9D10535055C2095");

                    b.ToTable("Otp", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.PCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("description");

                    b.Property<string>("Identity")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("identity");

                    b.HasKey("Id")
                        .HasName("PK__p_catego__3214EC0795538515");

                    b.ToTable("p_category", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.PFunction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("permission_key");

                    b.HasKey("Id")
                        .HasName("PK__p_functi__3214EC07D19C8E01");

                    b.HasIndex("CategoryId");

                    b.HasIndex(new[] { "PermissionKey" }, "UQ__p_functi__9E2779BD01846E20")
                        .IsUnique();

                    b.ToTable("p_function", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.PRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK__p_role__3214EC07B368DDB1");

                    b.HasIndex(new[] { "Name" }, "UQ__p_role__72E12F1BBF2AD974")
                        .IsUnique();

                    b.ToTable("p_role", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.ParentLinkRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__ParentLi__3214EC0720C12F86");

                    b.HasIndex("ParentId");

                    b.HasIndex("StudentId");

                    b.ToTable("ParentLinkRequests");
                });

            modelBuilder.Entity("Infrastructure.TempModels.ParentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__ParentPr__3214EC0761A9CA55");

                    b.ToTable("ParentProfile", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Password__3214EC07BFB33313");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Token" }, "UQ__Password__1EB4F8175944EB96")
                        .IsUnique();

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<decimal>("AmountVnd")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<DateTime?>("CapturedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("TxnRef")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id")
                        .HasName("PK__Payments__3214EC07BECFF7B9");

                    b.HasIndex("OrderId");

                    b.HasIndex(new[] { "TxnRef" }, "UQ__Payments__DE7ABA53BF5879A5")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Progress", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModuleItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PercentDone")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("ScorePct")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("StudentId", "ModuleItemId")
                        .HasName("PK__Progress__9CEE653A05D9D328");

                    b.HasIndex("ModuleItemId");

                    b.ToTable("Progress", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<decimal>("PassingScorePct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(50.00m);

                    b.Property<int?>("PickCount")
                        .HasColumnType("int");

                    b.Property<int?>("TimeLimitMin")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Quiz__3214EC07423BF1CC");

                    b.ToTable("Quiz", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.QuizAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<int>("AttemptNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeadlineAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("bit");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ScorePct")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__QuizAtte__3214EC070E7C79F7");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "QuizId", "StudentId", "AttemptNo" }, "UQ_QuizAttempt")
                        .IsUnique();

                    b.ToTable("QuizAttempt", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.QuizAttemptQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("DisplayOrder")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__QuizAtte__3214EC0793843CCD");

                    b.HasIndex("AttemptId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuizAttemptQuestion", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.QuizOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__QuizOpti__3214EC07D2B00FB3");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuizOption", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.QuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__QuizQues__3214EC0706B6327D");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizQuestion", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("Id")
                        .HasName("PK__Reviews__3214EC07C19495F3");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "CourseId", "StudentId" }, "UQ_Review")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Infrastructure.TempModels.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradeLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Institution")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__StudentP__3214EC07A84EDAD7");

                    b.HasIndex("ParentId");

                    b.ToTable("StudentProfile", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.StudentVocabulary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Antonyms")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Definition")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Example")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartOfSpeech")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phonetic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Synonyms")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__StudentV__3214EC074EFB6526");

                    b.HasIndex("UserId");

                    b.ToTable("StudentVocabulary", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.SystemKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("code_key");

                    b.Property<int>("CodeValue")
                        .HasColumnType("int")
                        .HasColumnName("code_value");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<int?>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("PK__SystemKe__3214EC074AF795E4");

                    b.HasIndex("ParentId");

                    b.HasIndex(new[] { "CodeKey", "CodeValue" }, "UQ_SystemKey_Code")
                        .IsUnique();

                    b.ToTable("SystemKey", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte?>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07E0D93620");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E490C1A94A")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534AF3DCAB6")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PRoleFunction", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<int>("FunctionId")
                        .HasColumnType("int")
                        .HasColumnName("function_id");

                    b.HasKey("RoleId", "FunctionId")
                        .HasName("PK__p_role_f__29C13F1CC669E777");

                    b.HasIndex("FunctionId");

                    b.ToTable("p_role_function", (string)null);
                });

            modelBuilder.Entity("PUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK__p_user_r__6EDEA1538933C941");

                    b.HasIndex("RoleId");

                    b.ToTable("p_user_role", (string)null);
                });

            modelBuilder.Entity("Infrastructure.TempModels.Assignment", b =>
                {
                    b.HasOne("Infrastructure.TempModels.ModuleItem", "IdNavigation")
                        .WithOne("Assignment")
                        .HasForeignKey("Infrastructure.TempModels.Assignment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Assignment__Id__084B3915");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Infrastructure.TempModels.AssignmentWork", b =>
                {
                    b.HasOne("Infrastructure.TempModels.Assignment", "Assignment")
                        .WithMany("AssignmentWorks")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Assignmen__Assig__0C1BC9F9");

                    b.HasOne("Infrastructure.TempModels.InstructorProfile", "Grader")
                        .WithMany("AssignmentWorks")
                        .HasForeignKey("GraderId")
                        .HasConstraintName("FK__Assignmen__Grade__0EF836A4");

                    b.HasOne("Infrastructure.TempModels.StudentProfile", "Student")
                        .WithMany("AssignmentWorks")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Assignmen__Stude__0D0FEE32");

                    b.Navigation("Assignment");

                    b.Navigation("Grader");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Infrastructure.TempModels.AttemptAnswer", b =>
                {
                    b.HasOne("Infrastructure.TempModels.QuizAttempt", "Attempt")
                        .WithMany("AttemptAnswers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__AttemptAn__Attem__047AA831");

                    b.HasOne("Infrastructure.TempModels.QuizOption", "ChosenOption")
                        .WithMany("AttemptAnswers")
                        .HasForeignKey("ChosenOptionId")
                        .IsRequired()
                        .HasConstraintName("FK__AttemptAn__Chose__056ECC6A");

                    b.Navigation("Attempt");

                    b.Navigation("ChosenOption");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Course", b =>
                {
                    b.HasOne("Infrastructure.TempModels.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Course__Category__373B3228");

                    b.HasOne("Infrastructure.TempModels.InstructorProfile", "CreatedByNavigation")
                        .WithMany("Courses")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK__Course__CreatedB__36470DEF");

                    b.Navigation("Category");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("Infrastructure.TempModels.CourseManager", b =>
                {
                    b.HasOne("Infrastructure.TempModels.Course", "Course")
                        .WithMany("CourseManagers")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CourseMan__Cours__44952D46");

                    b.HasOne("Infrastructure.TempModels.ManagerProfile", "User")
                        .WithMany("CourseManagers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__CourseMan__UserI__4589517F");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.TempModels.CoursePrice", b =>
                {
                    b.HasOne("Infrastructure.TempModels.Course", "Course")
                        .WithOne("CoursePrice")
                        .HasForeignKey("Infrastructure.TempModels.CoursePrice", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CoursePri__Cours__3DE82FB7");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Infrastructure.TempModels.CourseRequest", b =>
                {
                    b.HasOne("Infrastructure.TempModels.Course", "Course")
                        .WithMany("CourseRequests")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__CourseReq__Cours__39E294A9");

                    b.HasOne("Infrastructure.TempModels.ParentProfile", "Parent")
                        .WithMany("CourseRequests")
                        .HasForeignKey("ParentId")
                        .IsRequired()
                        .HasConstraintName("FK__CourseReq__Paren__3AD6B8E2");

                    b.HasOne("Infrastructure.TempModels.StudentProfile", "Student")
                        .WithMany("CourseRequests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CourseReq__Stude__38EE7070");

                    b.Navigation("Course");

                    b.Navigation("Parent");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Discussion", b =>
                {
                    b.HasOne("Infrastructure.TempModels.ModuleItem", "IdNavigation")
                        .WithOne("Discussion")
                        .HasForeignKey("Infrastructure.TempModels.Discussion", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Discussion__Id__11D4A34F");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Infrastructure.TempModels.DiscussionReply", b =>
                {
                    b.HasOne("Infrastructure.TempModels.User", "Author")
                        .WithMany("DiscussionReplies")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Discussio__Autho__178D7CA5");

                    b.HasOne("Infrastructure.TempModels.Discussion", "Discussion")
                        .WithMany("DiscussionReplies")
                        .HasForeignKey("DiscussionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Discussio__Discu__15A53433");

                    b.HasOne("Infrastructure.TempModels.DiscussionReply", "ParentReply")
                        .WithMany("InverseParentReply")
                        .HasForeignKey("ParentReplyId")
                        .HasConstraintName("FK__Discussio__Paren__1699586C");

                    b.Navigation("Author");

                    b.Navigation("Discussion");

                    b.Navigation("ParentReply");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Enrollment", b =>
                {
                    b.HasOne("Infrastructure.TempModels.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Enrollmen__Cours__4959E263");

                    b.HasOne("Infrastructure.TempModels.StudentProfile", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Enrollmen__Stude__4A4E069C");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Flashcard", b =>
                {
                    b.HasOne("Infrastructure.TempModels.FlashcardSet", "Set")
                        .WithMany("Flashcards")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Flashcard__SetId__29AC2CE0");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("Infrastructure.TempModels.FlashcardSet", b =>
                {
                    b.HasOne("Infrastructure.TempModels.StudentProfile", "Student")
                        .WithMany("FlashcardSets")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Flashcard__Stude__22FF2F51");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Infrastructure.TempModels.InstructorProfile", b =>
                {
                    b.HasOne("Infrastructure.TempModels.User", "IdNavigation")
                        .WithOne("InstructorProfile")
                        .HasForeignKey("Infrastructure.TempModels.InstructorProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__InstructorPr__Id__11158940");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Lesson", b =>
                {
                    b.HasOne("Infrastructure.TempModels.ModuleItem", "IdNavigation")
                        .WithOne("Lesson")
                        .HasForeignKey("Infrastructure.TempModels.Lesson", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Lesson__Id__5C6CB6D7");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Infrastructure.TempModels.LessonOption", b =>
                {
                    b.HasOne("Infrastructure.TempModels.LessonQuestion", "Question")
                        .WithMany("LessonOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LessonOpt__Quest__640DD89F");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Infrastructure.TempModels.LessonQuestion", b =>
                {
                    b.HasOne("Infrastructure.TempModels.Lesson", "Lesson")
                        .WithMany("LessonQuestions")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LessonQue__Lesso__603D47BB");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Infrastructure.TempModels.ManagerProfile", b =>
                {
                    b.HasOne("Infrastructure.TempModels.User", "IdNavigation")
                        .WithOne("ManagerProfile")
                        .HasForeignKey("Infrastructure.TempModels.ManagerProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ManagerProfi__Id__15DA3E5D");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Module", b =>
                {
                    b.HasOne("Infrastructure.TempModels.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Module__CourseId__50FB042B");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Infrastructure.TempModels.ModuleItem", b =>
                {
                    b.HasOne("Infrastructure.TempModels.Module", "Module")
                        .WithMany("ModuleItems")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ModuleIte__Modul__57A801BA");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Infrastructure.TempModels.OauthAccount", b =>
                {
                    b.HasOne("Infrastructure.TempModels.User", "User")
                        .WithMany("OauthAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__OAuthAcco__UserI__2EA5EC27");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Order", b =>
                {
                    b.HasOne("Infrastructure.TempModels.ParentProfile", "Parent")
                        .WithMany("Orders")
                        .HasForeignKey("ParentId")
                        .IsRequired()
                        .HasConstraintName("FK__Orders__ParentId__408F9238");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Infrastructure.TempModels.OrderItem", b =>
                {
                    b.HasOne("Infrastructure.TempModels.Course", "Course")
                        .WithMany("OrderItems")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderItem__Cours__4924D839");

                    b.HasOne("Infrastructure.TempModels.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__OrderItem__Order__473C8FC7");

                    b.HasOne("Infrastructure.TempModels.CourseRequest", "Request")
                        .WithMany("OrderItems")
                        .HasForeignKey("RequestId")
                        .HasConstraintName("FK__OrderItem__Reque__4830B400");

                    b.HasOne("Infrastructure.TempModels.StudentProfile", "Student")
                        .WithMany("OrderItems")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderItem__Stude__4A18FC72");

                    b.Navigation("Course");

                    b.Navigation("Order");

                    b.Navigation("Request");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Infrastructure.TempModels.PFunction", b =>
                {
                    b.HasOne("Infrastructure.TempModels.PCategory", "Category")
                        .WithMany("PFunctions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__p_functio__categ__6DCC4D03");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Infrastructure.TempModels.ParentLinkRequest", b =>
                {
                    b.HasOne("Infrastructure.TempModels.ParentProfile", "Parent")
                        .WithMany("ParentLinkRequests")
                        .HasForeignKey("ParentId")
                        .IsRequired()
                        .HasConstraintName("FK__ParentLin__Paren__22401542");

                    b.HasOne("Infrastructure.TempModels.StudentProfile", "Student")
                        .WithMany("ParentLinkRequests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ParentLin__Stude__214BF109");

                    b.Navigation("Parent");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Infrastructure.TempModels.ParentProfile", b =>
                {
                    b.HasOne("Infrastructure.TempModels.User", "IdNavigation")
                        .WithOne("ParentProfile")
                        .HasForeignKey("Infrastructure.TempModels.ParentProfile", "Id")
                        .IsRequired()
                        .HasConstraintName("FK__ParentProfil__Id__0697FACD");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Infrastructure.TempModels.PasswordResetToken", b =>
                {
                    b.HasOne("Infrastructure.TempModels.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__PasswordR__UserI__28ED12D1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Payment", b =>
                {
                    b.HasOne("Infrastructure.TempModels.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Payments__OrderI__4EDDB18F");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Progress", b =>
                {
                    b.HasOne("Infrastructure.TempModels.ModuleItem", "ModuleItem")
                        .WithMany("Progresses")
                        .HasForeignKey("ModuleItemId")
                        .IsRequired()
                        .HasConstraintName("FK__Progress__Module__1C5231C2");

                    b.HasOne("Infrastructure.TempModels.StudentProfile", "Student")
                        .WithMany("Progresses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Progress__Studen__1B5E0D89");

                    b.Navigation("ModuleItem");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Quiz", b =>
                {
                    b.HasOne("Infrastructure.TempModels.ModuleItem", "IdNavigation")
                        .WithOne("Quiz")
                        .HasForeignKey("Infrastructure.TempModels.Quiz", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Quiz__Id__67DE6983");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Infrastructure.TempModels.QuizAttempt", b =>
                {
                    b.HasOne("Infrastructure.TempModels.Quiz", "Quiz")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__QuizAttem__QuizI__7814D14C");

                    b.HasOne("Infrastructure.TempModels.StudentProfile", "Student")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__QuizAttem__Stude__7908F585");

                    b.Navigation("Quiz");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Infrastructure.TempModels.QuizAttemptQuestion", b =>
                {
                    b.HasOne("Infrastructure.TempModels.QuizAttempt", "Attempt")
                        .WithMany("QuizAttemptQuestions")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__QuizAttem__Attem__00AA174D");

                    b.HasOne("Infrastructure.TempModels.QuizQuestion", "Question")
                        .WithMany("QuizAttemptQuestions")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK__QuizAttem__Quest__019E3B86");

                    b.Navigation("Attempt");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Infrastructure.TempModels.QuizOption", b =>
                {
                    b.HasOne("Infrastructure.TempModels.QuizQuestion", "Question")
                        .WithMany("QuizOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__QuizOptio__Quest__725BF7F6");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Infrastructure.TempModels.QuizQuestion", b =>
                {
                    b.HasOne("Infrastructure.TempModels.Quiz", "Quiz")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__QuizQuest__QuizI__6D9742D9");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Review", b =>
                {
                    b.HasOne("Infrastructure.TempModels.Course", "Course")
                        .WithMany("Reviews")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__CourseI__30592A6F");

                    b.HasOne("Infrastructure.TempModels.StudentProfile", "Student")
                        .WithMany("Reviews")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__Student__314D4EA8");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Infrastructure.TempModels.StudentProfile", b =>
                {
                    b.HasOne("Infrastructure.TempModels.User", "IdNavigation")
                        .WithOne("StudentProfile")
                        .HasForeignKey("Infrastructure.TempModels.StudentProfile", "Id")
                        .IsRequired()
                        .HasConstraintName("FK__StudentProfi__Id__0B5CAFEA");

                    b.HasOne("Infrastructure.TempModels.ParentProfile", "Parent")
                        .WithMany("StudentProfiles")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK__StudentPr__Paren__0C50D423");

                    b.Navigation("IdNavigation");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Infrastructure.TempModels.StudentVocabulary", b =>
                {
                    b.HasOne("Infrastructure.TempModels.StudentProfile", "User")
                        .WithMany("StudentVocabularies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__StudentVo__UserI__1B9317B3");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.TempModels.SystemKey", b =>
                {
                    b.HasOne("Infrastructure.TempModels.SystemKey", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK__SystemKey__paren__7EF6D905");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PRoleFunction", b =>
                {
                    b.HasOne("Infrastructure.TempModels.PFunction", null)
                        .WithMany()
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__p_role_fu__funct__7755B73D");

                    b.HasOne("Infrastructure.TempModels.PRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__p_role_fu__role___76619304");
                });

            modelBuilder.Entity("PUserRole", b =>
                {
                    b.HasOne("Infrastructure.TempModels.PRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__p_user_ro__role___7B264821");

                    b.HasOne("Infrastructure.TempModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__p_user_ro__user___7A3223E8");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Assignment", b =>
                {
                    b.Navigation("AssignmentWorks");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Course", b =>
                {
                    b.Navigation("CourseManagers");

                    b.Navigation("CoursePrice");

                    b.Navigation("CourseRequests");

                    b.Navigation("Enrollments");

                    b.Navigation("Modules");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Infrastructure.TempModels.CourseRequest", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Discussion", b =>
                {
                    b.Navigation("DiscussionReplies");
                });

            modelBuilder.Entity("Infrastructure.TempModels.DiscussionReply", b =>
                {
                    b.Navigation("InverseParentReply");
                });

            modelBuilder.Entity("Infrastructure.TempModels.FlashcardSet", b =>
                {
                    b.Navigation("Flashcards");
                });

            modelBuilder.Entity("Infrastructure.TempModels.InstructorProfile", b =>
                {
                    b.Navigation("AssignmentWorks");

                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Lesson", b =>
                {
                    b.Navigation("LessonQuestions");
                });

            modelBuilder.Entity("Infrastructure.TempModels.LessonQuestion", b =>
                {
                    b.Navigation("LessonOptions");
                });

            modelBuilder.Entity("Infrastructure.TempModels.ManagerProfile", b =>
                {
                    b.Navigation("CourseManagers");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Module", b =>
                {
                    b.Navigation("ModuleItems");
                });

            modelBuilder.Entity("Infrastructure.TempModels.ModuleItem", b =>
                {
                    b.Navigation("Assignment");

                    b.Navigation("Discussion");

                    b.Navigation("Lesson");

                    b.Navigation("Progresses");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Infrastructure.TempModels.PCategory", b =>
                {
                    b.Navigation("PFunctions");
                });

            modelBuilder.Entity("Infrastructure.TempModels.ParentProfile", b =>
                {
                    b.Navigation("CourseRequests");

                    b.Navigation("Orders");

                    b.Navigation("ParentLinkRequests");

                    b.Navigation("StudentProfiles");
                });

            modelBuilder.Entity("Infrastructure.TempModels.Quiz", b =>
                {
                    b.Navigation("QuizAttempts");

                    b.Navigation("QuizQuestions");
                });

            modelBuilder.Entity("Infrastructure.TempModels.QuizAttempt", b =>
                {
                    b.Navigation("AttemptAnswers");

                    b.Navigation("QuizAttemptQuestions");
                });

            modelBuilder.Entity("Infrastructure.TempModels.QuizOption", b =>
                {
                    b.Navigation("AttemptAnswers");
                });

            modelBuilder.Entity("Infrastructure.TempModels.QuizQuestion", b =>
                {
                    b.Navigation("QuizAttemptQuestions");

                    b.Navigation("QuizOptions");
                });

            modelBuilder.Entity("Infrastructure.TempModels.StudentProfile", b =>
                {
                    b.Navigation("AssignmentWorks");

                    b.Navigation("CourseRequests");

                    b.Navigation("Enrollments");

                    b.Navigation("FlashcardSets");

                    b.Navigation("OrderItems");

                    b.Navigation("ParentLinkRequests");

                    b.Navigation("Progresses");

                    b.Navigation("QuizAttempts");

                    b.Navigation("Reviews");

                    b.Navigation("StudentVocabularies");
                });

            modelBuilder.Entity("Infrastructure.TempModels.SystemKey", b =>
                {
                    b.Navigation("InverseParent");
                });

            modelBuilder.Entity("Infrastructure.TempModels.User", b =>
                {
                    b.Navigation("DiscussionReplies");

                    b.Navigation("InstructorProfile");

                    b.Navigation("ManagerProfile");

                    b.Navigation("OauthAccounts");

                    b.Navigation("ParentProfile");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("StudentProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
